dependencies = []
description = "Repository of GitHub Actions of the organisation"
destination_server = []
flags = ["tools"]
languages = ["shell", "github-actions", "go", "javascript"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.2"
