---
name: Update Buildpack Inventory GitHub Action
description: |
  Add new releases to a buildpack inventory file.

inputs:
  repository:
    description: |
      Name of the repository where to check for new releases.
      (e.g. keycloak/keycloak)
    required: true
    default: ""

  inventory_file:
    description: |
      Path to the inventory file to update.
      Relative to GITHUB_WORKSPACE.
    required: false
    default: INVENTORY.tsv

  major_versions:
    description: |
      Space separated list of major versions to consider.
      This allows to handle multiple major versions in the same inventory file.
    required: true
    default: ""

  releases_limit:
    description: |
      Maximum number of releases to retain per requested major version.
      Must be a positive integer. If omitted, all releases are kept.
    required: false

  default_major:
    description: |
      When major versions has multiple values, allows to specify which one
      must be considered as the defaultable one.
      Defaults to the highest value of `major_versions` when no set or when set
      to a version that doesn't exist in `major_versions`.
    required: false
    default: ""

  pr_assignees:
    description: |
      Comma or newline-separated list of GitHub usernames to assign to the pull
      request.
    required: false

  pr_reviewers:
    description: |
      Comma or newline-separated list of GitHub usernames to request a pull
      request review from.
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v6
      if: ${{ github.repository != 'Scalingo/actions' }}
      with:
        fetch-depth: 0

    - name: Create Temporary File to Store New Releases
      id: releases_file
      shell: bash
      run: |
        releases_file="$( mktemp "${RUNNER_TEMP}/releases.XXXXXX" )"
        printf 'file=%s\n' "${releases_file}" >> "${GITHUB_OUTPUT}"

    - name: Get Latest Major Releases
      id: releases
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        MAJORS: ${{ inputs.major_versions }}
        RELEASES_FILE: ${{ steps.releases_file.outputs.file }}
      run: |
        "${GITHUB_ACTION_PATH}/scripts/get_latest_releases.sh" > "${RELEASES_FILE}"

    - name: Update Buildpack Inventory
      id: update_inventory
      shell: bash
      env:
        INVENTORY: ${{ inputs.inventory_file }}
        MAJORS: ${{ inputs.major_versions }}
        DEFAULT_MAJOR: ${{ inputs.default_major }}
        RELEASES_LIMIT: ${{ inputs.releases_limit }}
        RELEASES_FILE: ${{ steps.releases_file.outputs.file }}
      run: |
        "${GITHUB_ACTION_PATH}/scripts/update_buildpack_inventory.sh" < "${RELEASES_FILE}"

    - name: Create Pull Request
      id: pr
      uses: Scalingo/actions/create-pull-request@main
      with:
        branch: "feat/inventory/auto_update"
        delete-branch: true
        title: "chore(inventory): auto-update inventory"
        body: |
          This is an automated pull-request to update the inventory.
        commit-message: "chore(inventory): auto-update inventory"
        sign-commits: true
        assignees: ${{ inputs.pr_assignees }}
        reviewers: ${{ inputs.pr_reviewers }}
