name: pr-compliance

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - uses: Scalingo/actions/pull-request-compliance@main
        with:
          pr-title: ${{ github.event.pull_request.title }}
          pr-body: ${{ github.event.pull_request.body }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
