name: "Scalingo Lua linter GitHub Action"
description: "Lint Lua codebases with lua-language-server"

inputs:
  checklevel:
    description: >
      Minimum diagnostic level to log (Error, Warning, Information, Hint).
      Default is Warning but we set Hint to catch all diagnostics.
      See https://luals.github.io/wiki/usage/#--checklevel
    required: false
    default: "Hint"
  lua-path:
    description: >
      Custom Lua module search path (LUA_PATH environment variable).
      This is needed when a project has Lua modules in non-standard locations
      that the linter needs to resolve. Example: "./lua/packages/?.lua;;"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Restore lua-language-server cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/lua-language-server
        key: lua-language-server-${{ runner.os }}-latest

    - name: Install lua-language-server
      shell: bash
      run: "${GITHUB_ACTION_PATH}/scripts/install-lua-language-server.sh"

    - name: Lint Lua codebase
      shell: bash
      env:
        LUA_PATH: ${{ inputs.lua-path }}
        CHECKLEVEL: ${{ inputs.checklevel }}
      run: "${GITHUB_ACTION_PATH}/scripts/run-lua-lint.sh"
