name: "Scalingo Lua linter GitHub Action"
description: "Lint Lua codebases with lua-language-server"

inputs:
  checklevel:
    description: >
      Diagnostic severity filter: Error, Warning, Information, or Hint.
      Hint (default) reports everything. Error only reports critical issues.
    required: false
    default: "Hint"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install lua-language-server
      shell: bash
      run: "${GITHUB_ACTION_PATH}/scripts/install-lua-language-server.sh"

    - name: Lint Lua codebase
      shell: bash
      env:
        CHECKLEVEL: ${{ inputs.checklevel }}
      run: "${GITHUB_ACTION_PATH}/scripts/run-lua-lint.sh"
