---
name: ShellCheck GitHub Action
description: |
  Execute ShellCheck in a GitHub Action.

inputs:
  shellcheck-severity:
    description: |
      ShellCheck severity to use.
      One of 'error', 'warning', 'info', or 'style'.
    required: false
    default: style

  files:
    description: |
      List of files to scan.
      When unset, defaults to recursively scanning all .sh files in the repo.
    required: false
    default: ""

runs:
  using: "docker"
  image: "docker://koalaman/shellcheck-alpine:v0.11.0"
  entrypoint: /bin/sh
  args:
    - -c
    - |
      set -o errexit
      set -o nounset

      cd "${GITHUB_WORKSPACE:-/github/workspace}"

      if [ -n "${{ inputs.files }}" ]; then
          # Empty argv ($@):
          set --

          # Fill argv with the given files. Preserves spaces in filenames:
          while IFS= read -r file; do
              set -- "$@" "$file"
          done <<'EOF'
          ${{ inputs.files }}
          EOF

          # Call ShellCheck with input files:
          shellcheck -S "${{ inputs.shellcheck-severity }}" -s bash "$@"
      else
          find . -type f -name '*.sh' -not -path './.git/*' -exec \
            shellcheck -S "${{ inputs.shellcheck-severity }}" -s bash {} +
      fi
...
