---
name: ShellCheck GitHub Action
description: |
  Execute ShellCheck in a GitHub Action.

inputs:
  shellcheck-version:
    description: |
      ShellCheck version to use. This should match a Docker Hub tag.
      See https://hub.docker.com/r/koalaman/shellcheck/tags for a list of
      available tags.
    required: false
    default: "v0.11.0"

  shellcheck-severity:
    description: |
      ShellCheck severity to use.
      One of 'error', 'warning', 'info', or 'style'.
    required: false
    default: style

  files:
    description: |
      List of files to scan.
      When unset, defaults to recursively scanning all .sh files in the repo.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Run ShellCheck
      shell: bash
      run: |
        docker run --rm \
          --volume "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" \
          --workdir "$GITHUB_WORKSPACE" \
          koalaman/shellcheck-alpine:${{ inputs.shellcheck-version }} \
          sh -c <<'SCRIPT'

          set -o errexit
          set -o nounset"
          cd "${GITHUB_WORKSPACE}"

          severity="${{ inputs.shellcheck-severity }}"
          files="${{ inputs.files }}"

          if [ -n "${files}" ]; then
              set --

              while IFS= read -r file; do
                  [ -n "${file}" ] && set -- "$@" "${file}"
              done <<EOF
              ${files}
              EOF

              shellcheck -S "${severity}" -s bash "$@"
          else
              find . -type f -name '*.sh' -not -path './.git/*' \
                  -exec shellcheck -S "${severity}" -s bash {} +
          fi

          SCRIPT
