name: "Scalingo Go linter GitHub Action"
description: "Execute the Scalingo Go linter in a GitHub Action"

inputs:
  sqlc:
    description: "Install sqlc if needed. Possible values: true | false | auto"
    required: false
    default: "auto"
  working-directory:
    description: "Change the working directory for the tests execution. This must only be used if the Go code is not at the root of the repository. The default value should work for 99.9% of the projects."
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        # We need to define the fetch-depth to 0 so that we can get the commit ID of the master branch
        fetch-depth: 0
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v6
      with:
        go-version-file: "${{ inputs.working-directory }}/go.mod"
        check-latest: true
        cache-dependency-path: "${{ inputs.working-directory }}/go.sum"

    # Execute the `lint-go-version` script
    - name: Download the lint-go-version script
      shell: bash
      run: |
        wget --output-document=${working_directory}/lint-go-version https://sc-devtools.s3.eu-west-1.amazonaws.com/golang-ci/lint-go-version
        bash ${working_directory}/lint-go-version
      env:
        working_directory: ${{ inputs.working-directory }}

    - name: Determine if sqlc is needed
      id: sqlc_check
      shell: bash
      run: ${GITHUB_ACTION_PATH}/scripts/sqlc-check.sh >> $GITHUB_OUTPUT
      env:
        WITH_SQLC: "${{ inputs.sqlc }}"

    - name: "Check sqlc diff"
      if: ${{ steps.sqlc_check.outputs.configuration_file != '' }}
      shell: bash
      run: |
        go install "github.com/sqlc-dev/sqlc/cmd/sqlc@latest"
        sqlc diff --file $SQLC_CONFIGURATION_FILE
      env:
        SQLC_CONFIGURATION_FILE: "${{ steps.sqlc_check.outputs.configuration_file }}"

    # Execute golangci-lint
    - name: Download golangci-lint configuration file
      shell: bash
      run: wget --output-document=${working_directory}/.golangci.yml https://sc-devtools.s3.eu-west-1.amazonaws.com/golang-ci/golangci.yml
      env:
        working_directory: ${{ inputs.working-directory }}
    # Some projects have no vendor directory (mostly because they are actually a library)
    - name: "Configure modules download mode"
      shell: bash
      id: check_vendor
      run: |
        if [[ ! -d vendor ]]; then
          echo "modules_download_mode=--modules-download-mode=mod" >> $GITHUB_OUTPUT
        fi
    - name: "Execute golangci-lint on a pull request"
      uses: Scalingo/golangci-lint-action@v9
      with:
        working-directory: ${{ matrix.modules }}
        # The `only-new-issues` flag is not working (https://github.com/golangci/golangci-lint-action/issues/531).
        # We rather decided to use the suggestion from the FAQ (https://golangci-lint.run/docs/welcome/faq/#how-to-integrate-golangci-lint-into-a-large-project-with-thousands-of-issues) and use `--new-from-rev`
        # only-new-issues: false
        args: "--config=$(pwd)/.golangci.yml --new-from-rev=${{ github.event.pull_request.base.sha }} ${{ steps.check_vendor.outputs.modules_download_mode }}"
