name: definition-of-done

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Scalingo/actions/definition-of-done@main
        with:
          pr-body: ${{ github.event.pull_request.body }}
