name: "Scalingo Lua tests GitHub Action"
description: "Run Lua test suites with bin/specs"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      if: ${{ github.repository != 'Scalingo/actions' }}

    - name: "Export env file"
      shell: bash
      run: |
        set -euo pipefail
        test -f .env.test && grep -v '^#' .env.test >> "$GITHUB_ENV" || true


    - name: "Execute extra setup step"
      if: ${{ hashFiles('bin/scalingo-ci-extra-setup.sh') != '' }}
      shell: bash
      run: bin/scalingo-ci-extra-setup.sh

    - name: "Run tests"
      shell: bash
      run: bin/specs
