name: "Scalingo Lua tests GitHub Action"
description: "Run Lua test suites with a repository-provided command"

inputs:
  working-directory:
    description: "Directory to run tests from"
    required: false
    default: "."
  command:
    description: "Command to run tests (should be provided by the repository)"
    required: false
    default: "bin/specs"
  env-file:
    description: "Optional environment file to export before running tests"
    required: false
    default: ".env.test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      if: ${{ github.repository != 'Scalingo/actions' }}
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}

    - name: "Export env file"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENV_FILE: ${{ inputs.env-file }}
      run: |
        set -euo pipefail
        if [[ -f "${ENV_FILE}" ]]; then
          cat "${ENV_FILE}" >> "${GITHUB_ENV}"
        fi

    - name: "Execute extra setup step"
      if: ${{ hashFiles(format('{0}/bin/scalingo-ci-extra-setup.sh', inputs.working-directory)) != '' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bin/scalingo-ci-extra-setup.sh

    - name: "Run tests"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        COMMAND: ${{ inputs.command }}
      run: |
        set -euo pipefail
        ${COMMAND}
