name: "Scalingo Lua tests GitHub Action"
description: "Run Lua test suites with a repository-provided command"

inputs:
  env-file:
    description: "Optional environment file to export before running tests (path relative to repository root)"
    required: false
    default: ".env.test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      if: ${{ github.repository != 'Scalingo/actions' }}
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}

    - name: "Export env file"
      shell: bash
      env:
        ENV_FILE: ${{ inputs.env-file }}
      run: |
        set -euo pipefail
        if [[ -f "${ENV_FILE}" ]]; then
          cat "${ENV_FILE}" >> "${GITHUB_ENV}"
        fi

    - name: "Execute extra setup step"
      if: ${{ hashFiles('bin/scalingo-ci-extra-setup.sh') != '' }}
      shell: bash
      run: bin/scalingo-ci-extra-setup.sh

    - name: "Run tests"
      shell: bash
      run: |
        set -euo pipefail
        if [[ ! -x "bin/specs" ]]; then
          echo "Expected executable test runner at bin/specs but it was not found."
          exit 1
        fi
        bin/specs
