name: "Scalingo Go Rolling Release"
description: "Create pre-release of current revision based on the name of the previous release (ODR-38)"

### 
#
# name: publish-staging
# on:
#   workflow_run:
#     workflows: ["CI"]
#     branches: [ main, master ]
#     types:
#       - completed
# 
# permissions:
#   contents: write                # required to push tags & create releases
# 
# jobs:
#   prerelease:
#     runs-on: ubuntu-24.04
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
# 
#     environment:
#       name: staging
# 
#     steps:
#       - uses: Scalingo/actions/go-rolling-release@main
#         with:
#           - github_token: secrets.GITHUB_TOKEN

inputs:
  github_token:
    description: "GitHub token for API access. It is used to create tag and release."
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0          # required to create & push tags

    - name: Compute tag (UTC timestamp)
      id: meta
      shell: bash
      run: |
        set -euo pipefail
        # Try to find the latest semver-style tag like v1.2.3, fallback on
        # v0.0.0 if there is no tag yet
        LATEST_TAG="$((git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | grep --invert-match "patch" || true) | head --lines=1)"
        LATEST_TAG="${LATEST_TAG:-v0.0.0}"
        SHORT_SHA="$(git rev-parse --short HEAD)"
        TAG="${LATEST_TAG}-patch-${SHORT_SHA}"

        # Get a timestamp to have unique tags even when multiple pre-releases are created for the same commit
        TIMESTAMP="$(date +%Y%m%d%H%M%S)"
        TAG="${LATEST_TAG}-patch-${TIMESTAMP}-${SHORT_SHA}"
        echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
        echo "Generated tag: ${TAG}"

    - name: Create and push tag
      env:
        TAG: ${{ steps.meta.outputs.tag }}
      shell: bash
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag "${TAG}" --message "Automated pre-release from ${GITHUB_REF_NAME} at $(date --utc --iso-8601=seconds)"
        git push origin "${TAG}"

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
        check-latest: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --clean
      env:
        GORELEASER_CURRENT_TAG: ${{ steps.meta.outputs.tag }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CGO_ENABLED: 0

